# Generated by Django 3.2.12 on 2022-02-13 18:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('prepa', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grupo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grupo', models.CharField(max_length=10)),
                ('jefe_grupo', models.CharField(blank=True, max_length=20, null=True)),
                ('folio_grupo', models.CharField(blank=True, max_length=5, null=True)),
                ('postales', models.CharField(blank=True, max_length=5, null=True)),
                ('escuela', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='salon', to='prepa.escuela')),
            ],
        ),
    ]
