# Generated by Django 3.2.12 on 2022-02-13 18:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('prepa', '0002_grupo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('tipo_moldura', models.IntegerField(choices=[(1, 'PIRAMIDAL NEGRO'), (2, 'PIRAMIDAL VINO'), (3, 'PIRAMIDAL CAFE'), (4, 'ROLEX CAFE'), (5, 'ROLEX NEGRO'), (6, 'ROLEX VINO'), (9, 'CRISTAL GRANDE'), (10, 'MERCURIO'), (11, 'CORONA'), (12, 'ESTRELLA'), (14, 'MARIPOSA'), (15, 'ROMANA'), (16, 'MONACO'), (17, 'ANUBIS'), (18, 'ESLOVENIA'), (19, 'INGLESA'), (20, 'BERLIN'), (21, 'FLORENCIA')], null=True)),
                ('tipo_placa', models.IntegerField(default=1, null=True)),
                ('color_placa', models.IntegerField(default=1, null=True)),
                ('folio', models.CharField(blank=True, max_length=6, null=True)),
                ('pedido_extra', models.CharField(blank=True, max_length=20, null=True)),
                ('taza', models.DateField()),
                ('grupo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alumno', to='prepa.grupo')),
            ],
        ),
    ]
