# Generated by Django 3.2.12 on 2022-02-13 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prepa', '0004_auto_20220213_1221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generacion',
            name='generacion',
            field=models.DateField(),
        ),
    ]
