# Generated by Django 3.2.12 on 2022-02-13 18:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('prepa', '0006_pago'),
    ]

    operations = [
        migrations.AddField(
            model_name='pago',
            name='fecha',
            field=models.DateField(null=True),
        ),
        migrations.CreateModel(
            name='Control',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto_enviada', models.DateField(blank=True, null=True)),
                ('archivo_foto', models.CharField(blank=True, max_length=25, null=True)),
                ('placa_enviada', models.DateField(blank=True, null=True)),
                ('archivo_placa', models.CharField(blank=True, max_length=25, null=True)),
                ('foto_recibida', models.DateField(blank=True, null=True)),
                ('placa_recibida', models.DateField(blank=True, null=True)),
                ('foto_armada', models.DateField(blank=True, null=True)),
                ('foto_entregada', models.DateField(blank=True, null=True)),
                ('nombre', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='control', to='prepa.alumno')),
            ],
        ),
    ]
