# Generated by Django 3.2.12 on 2022-02-16 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prepa', '0009_auto_20220215_2055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumno',
            name='color_placa',
            field=models.IntegerField(choices=[(0, '---'), (1, 'CAFE'), (2, 'NEGRO'), (3, 'ROJO'), (4, 'AZUL'), (5, 'VERDE'), (6, 'PLATA')], default=1, null=True),
        ),
    ]
