# Generated by Django 3.2.12 on 2022-02-16 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prepa', '0011_auto_20220215_2056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumno',
            name='taza',
            field=models.DateField(blank=True, null=True),
        ),
    ]
