# Generated by Django 3.2.12 on 2022-02-16 03:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prepa', '0013_grupo_generacion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grupo',
            name='generacion',
        ),
    ]
