# Generated by Django 3.2.12 on 2022-02-18 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prepa', '0015_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
