# Generated by Django 3.2.12 on 2022-02-19 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prepa', '0016_delete_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumno',
            name='tipo_placa',
            field=models.CharField(choices=[(12, '---'), (1, 'MEDITERRANEA'), (2, '4 PIEZAS'), (3, 'PELLISCO'), (4, 'PLANA'), (5, 'CORTE PLANO'), (6, 'CORAZON'), (7, 'PALERMO'), (8, 'PERGAMINO'), (9, 'COLUMNAS'), (10, 'CIRCULO'), (11, 'piramide')], default=1, max_length=20, null=True),
        ),
    ]
