# Generated by Django 3.2.12 on 2022-02-21 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prepa', '0017_alter_alumno_tipo_placa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumno',
            name='tipo_moldura',
            field=models.IntegerField(choices=[('PIRAMIDAL NEGRO', 'PIRAMIDAL NEGRO'), ('PIRAMIDAL VINO', 'PIRAMIDAL VINO'), ('PIRAMIDAL CAFE', 'PIRAMIDAL CAFE'), (4, 'ROLEX CAFE'), (5, 'ROLEX NEGRO'), (6, 'ROLEX VINO'), (9, 'CRISTAL GRANDE'), (10, 'MERCURIO'), (11, 'CORONA'), (12, 'ESTRELLA'), (14, 'MARIPOSA'), (15, 'ROMANA'), (16, 'MONACO'), (17, 'ANUBIS'), (18, 'ESLOVENIA'), (19, 'INGLESA'), (20, 'BERLIN'), (21, 'FLORENCIA'), (22, 'RESINA'), (23, 'CRISTAL CHICO')], null=True),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='tipo_placa',
            field=models.CharField(choices=[(12, '---'), (1, 'MEDITERRANEA'), (2, '4 PIEZAS'), (3, 'PELLISCO'), (4, 'PLANA'), (5, 'CORTE PLANO'), (6, 'CORAZON'), (7, 'PALERMO'), (8, 'PERGAMINO'), (9, 'COLUMNAS'), (10, 'CIRCULO'), (11, 'piramide')], default='PIRAMIDAL NEGRO', max_length=20, null=True),
        ),
    ]
